---
- name: Delete Grafana access on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    src: files/grafana/grafana-setup.yaml

- name: Delete Grafana operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    src: files/grafana/grafana-operator.yaml

- name: Delete Grafana operator on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ item.name }}"
    namespace: "{{ item.monitoring_namespace }}"
    state: absent
    src: files/grafana/grafana-operator.yaml
  loop: "{{ workers }}"

- name: Delete Grafana instance on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    src: files/grafana/grafana.yaml

- name: Delete Grafana instance on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ item.name }}"
    namespace: "{{ item.monitoring_namespace }}"
    state: absent
    src: files/grafana/grafana.yaml
  loop: "{{ workers }}"

- name: Remove Alertmanager  configuration for sending alerts on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: absent
    template: templates/alert-manager-configuration.yaml.j2

- name: Remove Alertmanager configuration for sending alerts on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ item.name }}"
    state: absent
    template: templates/alert-manager-configuration.yaml.j2
  loop: "{{ workers }}"

- name: Delete Grafana dashboards and Prometheus alerts
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    src: "files/argo/metrics/{{ item }}"
  loop:
    - alerts.yaml
    - argo-dashboard-cm.yaml
    - grafana-argo-dashboards.yaml

- name: Delete Grafana data-source on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_monitoring_namespace }}"
    state: absent
    template: templates/grafana-data-source.yaml.j2

- name: Delete Grafana data-source on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ item.name }}"
    namespace: "{{ item.monitoring_namespace }}"
    state: absent
    template: templates/grafana-data-source.yaml.j2
  loop: "{{ workers }}"

- name: Delete monitoring namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ infra_monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent

- name: Delete monitoring namespaces on Worker clusters
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ item.name }}"
    name: "{{ item.monitoring_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  loop: "{{ workers }}"