---
- name: Export access token
  shell: "oc serviceaccounts get-token grafana-serviceaccount -n {{ item.monitoring_namespace }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ item.name }}"
  register: "access_token_out"

- name: Set facts for route host
  set_fact: access_token="{{ access_token_out.stdout }}"

- name: Check that token exists
  fail:
    msg: "Token is not properly stored!\n{{ access_token }}"
  when: access_token | length == 0

- name: Create Grafana data-source
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ item.name }}"
    namespace: "{{ item.monitoring_namespace }}"
    state: present
    template: templates/grafana-data-source.yaml.j2