---
# tasks file for tealc

# clusters connections
- import_tasks: common/check_parameters.yaml
  tags: [always, check-params]

- import_tasks: common/check_clients.yaml
  tags: [always, check-clients]

- import_tasks: common/prepare_kubeconfigs.yaml
  tags: [always, kubeconfigs]


# infra installation
- import_tasks: infra-setup/access_remote_cluster.yaml
  tags: [setup-workers-access, strimzi-infra]

- import_tasks: infra-setup/install_tekton.yaml
  tags: [tekton, strimzi-infra]

- import_tasks: infra-setup/install_argo.yaml
  tags: [argo, strimzi-infra]

- import_tasks: monitoring/install_monitoring.yaml
  tags: [monitoring, grafana, strimzi-infra]
  when: not is_kubernetes


# Scenarios
- import_tasks: scenario-deployment/argo-deploy-strimzi-infra.yaml
  tags: [argo-apps, argo-strimzi-infra, strimzi-infra]

- import_tasks: scenario-deployment/argo-deploy-strimzi-clients.yaml
  tags: [argo-apps, argo-strimzi-clients, strimzi-infra]

- import_tasks: scenario-deployment/argo-deploy-strimzi-monitoring.yaml
  tags: [argo-apps, argo-strimzi-monitoring, strimzi-infra]

- import_tasks: scenario-deployment/argo-deploy-strimzi-twitter-app.yaml
  tags: [argo-apps, argo-strimzi-twitter-app, twitter-app]

- import_tasks: scenario-deployment/strimzi-infra-tkn-pipelines.yaml
  tags: [tekton-pipelines, strimzi-infra]
  when: not is_kubernetes


# Teardown
- import_tasks: infra-setup/delete_argo.yaml
  tags: [never, teardown, teardown-argo]

- import_tasks: infra-setup/delete_tekton.yaml
  tags: [never, teardown, teardown-tekton]

- import_tasks: monitoring/delete_monitoring.yaml
  tags: [never, teardown, teardown-monitoring]
  when: not is_kubernetes