apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: scale-worker-cluster-start
  labels:
    app: tealc
spec:
  pipelineRef:
    name: scale-worker-cluster-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: scale-worker-cluster-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
---

apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: scale-worker-cluster-start
  labels:
    app: tealc
spec:
  pipelineRef:
    name: scale-worker-cluster-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: pipeline-ws
      volumeClaimTemplate:
        metadata:
          name: scale-worker-cluster-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
