---
- name: Create Test Tekton pipelines
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "files/tekton/pipelines/test/{{ item }}"
  loop:
    - test.yaml
    - test2.yaml

- name: Create Strimzi related Tekton pipelines
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_ci_namespace }}"
    state: present
    src: "files/tekton/pipelines/strimzi-deployment/{{ item }}"
  loop:
    - canary-image-updater.yaml
    - drain-cleaner-image-updater.yaml
    - strimzi-image-updater.yaml

- name: Create Strimzi-clients Tekton pipeline
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    template: "templates/tekton/pipelines/clients-update.yaml.j2"
  vars:
    worker_secret_prefix: "{{ workers[0].name }}"