---
- name: Create Argo applications for Strimzi
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: present
    template: "{{ item }}"
  vars:
    worker_cluster_connection: "{{ workers[0].name }}"
  with_fileglob: 'templates/argo/projects/*.j2'

