apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apophis-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: apophis-daily
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: apophis-storage
              persistentVolumeClaim:
                claimName: apophis-claim
          restartPolicy: OnFailure
          containers:
            - name: apophis-daily
              image: quay.io/tealc/apophis:latest
              imagePullPolicy: Always
              env:
                - name: CURRENT_DEPLOYMENT_REPO
                  value: "https://github.com/ExcelentProject/sokar"
                - name: YAML_BUNDLE_PATH
                  value: "./strimzi-cluster-operator/"
                - name: TARGET_ORG_REPO
                  value: "quay.io/strimzi"
                - name: BRANCH
                  value: main
                - name: SYNC_CRD_REPO
                  value: "https://github.com/strimzi/strimzi-kafka-operator"
                - name: SYNC_CRD_PATH
                  value: "install/cluster-operator"
                - name: GITHUB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: github-secret
                      key: USERNAME
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-secret
                      key: TOKEN
              volumeMounts:
                - mountPath: "/home/apophisuser/tealc"
                  name: apophis-storage
