---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-serviceaccount
  namespace: default
  labels:
    app: strimzi
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-binding
  labels:
    app: strimzi
subjects:
  - kind: ServiceAccount
    name: access-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io