apiVersion: v1
kind: Namespace
metadata:
  name: tealc-install
  labels:
    app: tealc
---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: tealc-install
  namespace: tealc-install
  labels:
    app: tealc
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tealc-install-binding
  labels:
    app: tealc
subjects:
  - kind: ServiceAccount
    name: tealc-install
    namespace: tealc-install
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: v1
kind: Pod
metadata:
  name: tealc-install
  namespace: tealc-install
  labels:
    app: tealc
spec:
  backoffLimit: 5
  serviceAccountName: tealc-install
  securityContext:
    runAsUser: 1000
  containers:
    - name: install
      image: quay.io/tealc/apophis:latest
      env:
        - name: HOME
          value: "/tmp"
        - name: GIT_CRYPT_KEY
          valueFrom:
            secretKeyRef:
              name: git-crypt-key
              key: key
      command:
        - "bin/bash"
        - "-c"
        - >-
          cd /tmp;
          git clone --branch main https://github.com/ExcelentProject/tealc.git;
          cd tealc;
          echo "$GIT_CRYPT_KEY" | base64  -d > ./git-crypt-key;
          git-crypt unlock ./git-crypt-key;
          ansible-galaxy collection install community.kubernetes;
          ansible-playbook install/ansible/tealc-play.yaml --tags infra,rp,strimzi-infra,twitter-app,test-suite --extra-vars log_sensitive_data=true
  restartPolicy: Never