---
- name: Delete Argo
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: absent
    src: files/argo/install/argo-install.yaml

- name: Delete Argo route
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: absent
    src: files/argo/install/argo-route.yaml

- name: Delete Argo config map
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: absent
    template: templates/argo/install/argocd-cm.yaml.j2

- name: Delete Argo rbac
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ infra_argo_namespace }}"
    state: absent
    src: files/argo/install/argocd-rbac-cm.yaml

- name: Delete Argo namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ infra_argo_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent