---
- name: Create Tekton namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ infra_ci_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create Tekton subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: present
    src: files/tekton/install/tekton-subscription.yaml
  when: not is_kubernetes

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
  when: not is_kubernetes

- name: Wait for Tekton operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_operators_namespace }}"
    kind: Deployment
    name: openshift-pipelines-operator
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  when: not is_kubernetes

- name: Create Tekton config
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-config.yaml
  when: not is_kubernetes

- name: Create Tekton dashboard
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-dashboard.yaml
  when: not is_kubernetes

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
  when: not is_kubernetes

- name: Wait for Tekton pipelines controller on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    kind: Deployment
    name: tekton-pipelines-controller
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  when: not is_kubernetes

- name: Wait for Tekton dashboard on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    kind: Deployment
    name: tekton-dashboard
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  when: not is_kubernetes

- name: Expose Tekton dashboard
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-dashboard-route.yaml
  when: not is_kubernetes

######################################################################################
######################################################################################
######################################################################################
- name: Create Tekton operator namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ tekton_operator_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  when: is_kubernetes

- name: Create Tekton pipelines namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ tekton_pipelines_namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
  when: is_kubernetes

- name: Install Tekton
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ tekton_operator_namespace }}"
    state: present
    src: files/tekton/install/tekton-release.yaml
  when: is_kubernetes

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
  when: is_kubernetes

- name: Wait for Tekton pipelines operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ tekton_operator_namespace }}"
    kind: Deployment
    name: tekton-operator
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  when: is_kubernetes

- name: Install Tekton CR
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ tekton_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-config-kube.yaml
  when: is_kubernetes

- name: Install Tekton dashboard
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ tekton_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-dashboard-kube.yaml
  when: is_kubernetes

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10
  when: is_kubernetes

- name: Wait for Tekton pipelines controller on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ tekton_pipelines_namespace }}"
    kind: Deployment
    name: tekton-pipelines-controller
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  when: is_kubernetes

- name: Wait for Tekton pipelines dashboard on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ tekton_pipelines_namespace }}"
    kind: Deployment
    name: tekton-dashboard
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  when: is_kubernetes
