---
- name: Create Tekton namespace on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    name: "{{ infra_ci_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create Tekton subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    state: present
    src: files/tekton/install/tekton-subscription.yaml

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Wait for Tekton operator on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_operators_namespace }}"
    kind: Deployment
    name: openshift-pipelines-operator
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable

- name: Create Tekton config
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-config.yaml

- name: Create Tekton dashboard
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-dashboard.yaml

- name: Sleep for 10 seconds and continue with play
  wait_for:
    timeout: 10

- name: Wait for Tekton pipelines controller on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    kind: Deployment
    name: tekton-pipelines-controller
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable

- name: Wait for Tekton dashboard on Infra cluster
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    kind: Deployment
    name: tekton-dashboard
    wait: true
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable

- name: Expose Tekton dashboard
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}/{{ infra_context_name }}"
    namespace: "{{ openshift_pipelines_namespace }}"
    state: present
    src: files/tekton/install/tekton-dashboard-route.yaml