---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
  namespace: tealc-monitoring
  labels:
    app: tealc
    namespace: tealc-monitoring
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-binding
  labels:
    app: tealc
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: tealc-monitoring
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
