---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: tealc-monitoring
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    security:
      admin_user: "admin"
      admin_password: "admin"
    auth:
      disable_login_form: False
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  resources:
    limits:
      cpu: 2000m
      memory: 8000Mi
    requests:
      cpu: 100m
      memory: 200Mi
  secrets:
    - grafana-k8s-proxy
    configMaps:
      - ocp-injected-certs
    service:
      ports:
        - name: grafana-proxy
          port: 9091
          protocol: TCP
          targetPort: grafana-proxy
    ingress:
      enabled: True
      targetPort: grafana-proxy
      termination: reencrypt
    client:
      preferService: True
    serviceAccount:
      annotations:
        serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}'
    dashboardLabelSelector:
      - matchExpressions:
          - {key: app, operator: In, values: [tealc]}