---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-group
  labels:
    app: grafana
spec:
  targetNamespaces:
    - tealc-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
spec:
  channel: v4
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
