---
- name: Check that kubeconfigs exists
  stat:
    path: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: kubeconfig_exists

- name: Create kubeconfig for Infra
  shell: " oc login -u {{ infra_username }} -p {{ infra_password }} --insecure-skip-tls-verify=true {{ infra_api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: not kubeconfig_exists.stat.exists and infra_access_token is not defined

- name: Create kubeconfig for Infra
  shell: " oc login --token {{ infra_access_token }} --insecure-skip-tls-verify=true {{ infra_api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: not kubeconfig_exists.stat.exists and infra_access_token is defined

- name: Create kubeconfig for Worker
  shell: "oc login -u {{ item.username }} -p {{ item.password }} --insecure-skip-tls-verify=true {{ item.api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ item.name }}"
  loop: "{{ workers }}"
  when: not kubeconfig_exists.stat.exists and workers[0].access_token is not defined

- name: Create kubeconfig for Worker
  shell: "oc login --token {{ item.access_token }} --insecure-skip-tls-verify=true {{ item.api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ item.name }}"
  loop: "{{ workers }}"
  when: not kubeconfig_exists.stat.exists and workers[0].access_token is defined

- name: test
  shell: cat "{{ kubeconfig_path }}/tealc-infra"