---
- name: Check that kubeconfigs exists
  stat:
    path: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  register: kubeconfig_exists

- name: Create kubeconfig for Infra
  shell: " oc login -u {{ infra_username }} -p {{ infra_password }} --insecure-skip-tls-verify=true {{ infra_api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ infra_context_name }}"
  when: not kubeconfig_exists.stat.exists

- name: Create kubeconfig for Worker
  shell: "oc login -u {{ item.username }} -p {{ item.password }} --insecure-skip-tls-verify=true {{ item.api_url }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}/{{ item.name }}"
  loop: "{{ workers }}"
  when: not kubeconfig_exists.stat.exists