---
- name: Check that kubeconfigs exists
  stat:
    path: "../kubeconfig/{{ infra_context_name }}"
  register: kubeconfig_exists

- name: Create kubeconfig for Infra
  shell: "KUBECONFIG=../kubeconfig/{{ infra_context_name }} oc login -u {{ infra_username }} -p {{ infra_password }} --insecure-skip-tls-verify=true {{ infra_api_url }}"
  when: not kubeconfig_exists.stat.exists

- name: Create kubeconfig for Worker
  shell: "KUBECONFIG=../kubeconfig/{{ item.name }} oc login -u {{ item.username }} -p {{ item.password }} --insecure-skip-tls-verify=true {{ item.api_url }}"
  loop: "{{ workers }}"
  when: not kubeconfig_exists.stat.exists