apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
stringData:
  admin.password: "$2y$10$oWia.FHl67boDIql.ifYruVdtk38ME905d5UqGmzvGCBG5NVuHg4G" #admin
  admin.passwordMtime: 2021-07-15T08:53:49CEST
