apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 10m

    route:
      group_by: ['alertname']
      group_wait: 1m
      group_interval: 5m
      repeat_interval: 24h
      receiver: 'default_blackhole'
      routes:
        - receiver: email
          match:
            app: tealc

    receivers:
    - name: 'default_blackhole'
    - name: 'email'
      email_configs:
      - to: 'tealc@redhat.com'
        from: 'tealc@redhat.com'
        smarthost: email-smtp.us-east-2.amazonaws.com:2587
        require_tls: true
        auth_username: AUTH_USERNAME
        auth_password: AUTH_PASSWORD
        send_resolved: true

