---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: argocd-server
  namespace: argocd
spec:
  host: ROUTE_HOST_PLACEHOLDER
  to:
    kind: Service
    name: argocd-server
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None