name: Apophis Image Build
on:
  push:
    paths:
      - "image-build/Dockerfile"
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
    paths:
      - "image-build/Dockerfile"

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to quay.io Hub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./image-update
          file: ./image-update/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: quay.io/tealc/apophis:latest
