name: Verify
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Kind
        uses: helm/kind-action@v1.2.0

      - name: Install tekton
        run: |
          ./scripts/install-tekton.sh

      - name: Print kube status
        if: failure()
        run: |
          kubectl get ns
          echo "--------------------------------------"
          kubectl get po --all-namespaces
          echo "--------------------------------------"
          kubectl get events --all-namespaces
          echo "--------------------------------------"
          kubectl get tektonconfig config -o yaml
          echo "--------------------------------------"
          kubectl logs deployment/tekton-operator -n tekton-operator
