name: Verify
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.20.0'
          kubernetes version: 'v1.21.2'
          start args: '--addons=registry,storage --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000" --extra-config=kubeadm.ignore-preflight-errors=SystemVerification --extra-config=apiserver.authorization-mode=RBAC,Node'

      - name: Install tekton
        run: |
          ./scripts/install-tekton.sh

      - name: Print kube status
        if: failure()
        run: |
          kubectl get ns
          echo "--------------------------------------"
          kubectl get po --all-namespaces
          echo "--------------------------------------"
          kubectl get events --all-namespaces
          echo "--------------------------------------"
          kubectl get tektonconfig config -o yaml
          echo "--------------------------------------"
          kubectl logs deployment/tekton-operator -n tekton-operator
