name: Verify
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Unlock
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

      - name: Setup Kind
        uses: helm/kind-action@v1.2.0

      - name: Install tekton
        run: |
          ./scripts/install-tekton.sh

      - name: Try test pipeline
        run: |
          ./.github/workflows/test-scripts/run-test-pipeline.sh

      - name: Deploy argo entrypoint
        run: |
          ./.github/workflows/test-scripts/install-argo-entrypoint.sh

      - name: Print kube status
        if: failure()
        run: |
          kubectl get ns
          echo "--------------------------------------"
          kubectl get po --all-namespaces
          echo "--------------------------------------"
          kubectl get events --all-namespaces
          echo "--------------------------------------"
          kubectl get pipelinerun --allnamespaces
          echo "--------------------------------------"
          kubectl get taskrun --allnamespaces
          echo "--------------------------------------"
          kubectl get pipeline --allnamespaces
          echo "--------------------------------------"
          kubectl get task --allnamespaces
