name: Yamllint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Unlock
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
