config_data: |
  extends: default
  rules:
    new-line-at-end-of-file:
      level: warning
    trailing-spaces:
      level: warning
    line-length:
      level: disabled
    document-start:
      level: disabled