apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: strimzi-cluster-operator
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: kafka
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-kafka
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-canary
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: strimzi-canary
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-kafka
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-clients
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: clients
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-clients
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: metrics
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-monitoring
