apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: strimzi-cluster-operator
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-operator
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: kafka
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-kafka
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-clients
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: clients
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: tealc-access
    namespace: strimzi-clients
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-options: Replace=true
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/sokar
    targetRevision: HEAD
    path: metrics
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
  destination:
    name: tealc-access
    namespace: strimzi-monitoring
  ignoreDifferences:
    - kind: ServiceAccount
      jsonPointers:
      - /metadata
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-update
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  project: default
  source:
    repoURL: https://github.com/ExcelentProject/tealc
    targetRevision: docs
    path: pipelines/strimzi-deployment
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tealc-ci