apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tealc-ci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/obabec/tealc
    targetRevision: entrypoint
    path: pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
